// Mocks generated by Mockito 5.4.6 from annotations
// in prebid_mobile_flutter/test/mock_host_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:prebid_mobile_flutter/src/generated/prebid_api.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInitializationResult_0 extends _i1.SmartFake
    implements _i2.InitializationResult {
  _FakeInitializationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiformatBidResult_1 extends _i1.SmartFake
    implements _i2.MultiformatBidResult {
  _FakeMultiformatBidResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrebidMobileHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrebidMobileHostApi extends _i1.Mock
    implements _i2.PrebidMobileHostApi {
  MockPrebidMobileHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.InitializationResult> initializeSdk(
    String? prebidServerUrl,
    String? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initializeSdk, [prebidServerUrl, accountId]),
            returnValue: _i4.Future<_i2.InitializationResult>.value(
              _FakeInitializationResult_0(
                this,
                Invocation.method(#initializeSdk, [prebidServerUrl, accountId]),
              ),
            ),
          )
          as _i4.Future<_i2.InitializationResult>);

  @override
  _i4.Future<void> setTimeoutMillis(int? timeoutMillis) =>
      (super.noSuchMethod(
            Invocation.method(#setTimeoutMillis, [timeoutMillis]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShareGeoLocation(bool? share) =>
      (super.noSuchMethod(
            Invocation.method(#setShareGeoLocation, [share]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPbsDebug(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setPbsDebug, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomHeaders(Map<String, String>? headers) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomHeaders, [headers]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStoredAuctionResponse(String? response) =>
      (super.noSuchMethod(
            Invocation.method(#setStoredAuctionResponse, [response]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearStoredAuctionResponse() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredAuctionResponse, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addStoredBidResponse(String? bidder, String? responseId) =>
      (super.noSuchMethod(
            Invocation.method(#addStoredBidResponse, [bidder, responseId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearStoredBidResponses() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredBidResponses, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLogLevel(int? level) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [level]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCreativeFactoryTimeout(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setCreativeFactoryTimeout, [timeout]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCreativeFactoryTimeoutPreRenderContent(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setCreativeFactoryTimeoutPreRenderContent, [
              timeout,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomStatusEndpoint(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomStatusEndpoint, [endpoint]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setExternalUserIds(List<_i2.ExternalUserIdData>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#setExternalUserIds, [userIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ExternalUserIdData>> getExternalUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#getExternalUserIds, []),
            returnValue: _i4.Future<List<_i2.ExternalUserIdData>>.value(
              <_i2.ExternalUserIdData>[],
            ),
          )
          as _i4.Future<List<_i2.ExternalUserIdData>>);

  @override
  _i4.Future<void> clearExternalUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#clearExternalUserIds, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getSdkVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getSdkVersion, []),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getSdkVersion, []),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [TargetingHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTargetingHostApi extends _i1.Mock implements _i2.TargetingHostApi {
  MockTargetingHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> setSubjectToCOPPA(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSubjectToCOPPA, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getSubjectToCOPPA() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectToCOPPA, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setSubjectToGDPR(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSubjectToGDPR, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getSubjectToGDPR() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectToGDPR, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setGDPRConsentString(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGDPRConsentString, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getGDPRConsentString() =>
      (super.noSuchMethod(
            Invocation.method(#getGDPRConsentString, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setPurposeConsents(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPurposeConsents, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPurposeConsents() =>
      (super.noSuchMethod(
            Invocation.method(#getPurposeConsents, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool?> getDeviceAccessConsent() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceAccessConsent, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setUSPrivacyString(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUSPrivacyString, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUSPrivacyString() =>
      (super.noSuchMethod(
            Invocation.method(#getUSPrivacyString, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> addUserKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#addUserKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addUserKeywords(List<String>? keywords) =>
      (super.noSuchMethod(
            Invocation.method(#addUserKeywords, [keywords]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserKeywords, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getUserKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#getUserKeywords, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addAppKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#addAppKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addAppKeywords(List<String>? keywords) =>
      (super.noSuchMethod(
            Invocation.method(#addAppKeywords, [keywords]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAppKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAppKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppKeywords, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addAppExtData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#addAppExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateAppExtData(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAppExtData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppExtData, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAppExtData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppExtData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addUserExtData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#addUserExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserExtData(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserExtData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserExtData, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserExtData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserExtData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addBidderToAccessControlList(String? bidderName) =>
      (super.noSuchMethod(
            Invocation.method(#addBidderToAccessControlList, [bidderName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeBidderFromAccessControlList(String? bidderName) =>
      (super.noSuchMethod(
            Invocation.method(#removeBidderFromAccessControlList, [bidderName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAccessControlList() =>
      (super.noSuchMethod(
            Invocation.method(#clearAccessControlList, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setGlobalOrtbConfig(String? ortbConfig) =>
      (super.noSuchMethod(
            Invocation.method(#setGlobalOrtbConfig, [ortbConfig]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getGlobalOrtbConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalOrtbConfig, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setContentUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setContentUrl, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPublisherName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setPublisherName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStoreUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setStoreUrl, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDomain(String? domain) =>
      (super.noSuchMethod(
            Invocation.method(#setDomain, [domain]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [InterstitialAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterstitialAdHostApi extends _i1.Mock
    implements _i2.InterstitialAdHostApi {
  MockInterstitialAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(
    int? adId,
    String? configId,
    List<String>? adFormats,
    _i2.VideoParametersConfig? videoConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [
              adId,
              configId,
              adFormats,
              videoConfig,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#show, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RewardedAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRewardedAdHostApi extends _i1.Mock implements _i2.RewardedAdHostApi {
  MockRewardedAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(int? adId, String? configId) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [adId, configId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#show, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NativeAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeAdHostApi extends _i1.Mock implements _i2.NativeAdHostApi {
  MockNativeAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(int? adId, _i2.NativeAdRequestConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [adId, config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackImpression(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#trackImpression, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackClick(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#trackClick, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [MultiformatAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiformatAdHostApi extends _i1.Mock
    implements _i2.MultiformatAdHostApi {
  MockMultiformatAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.MultiformatBidResult> fetchDemand(
    int? adId,
    _i2.MultiformatAdRequestConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDemand, [adId, config]),
            returnValue: _i4.Future<_i2.MultiformatBidResult>.value(
              _FakeMultiformatBidResult_1(
                this,
                Invocation.method(#fetchDemand, [adId, config]),
              ),
            ),
          )
          as _i4.Future<_i2.MultiformatBidResult>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
