// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPrebidApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPrebidApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPrebidApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPrebidApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPrebidApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPrebidApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Result of SDK initialization.
///
/// Generated class from Pigeon that represents data sent in messages.
struct InitializationResult: Hashable {
  var status: String
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializationResult? {
    let status = pigeonVar_list[0] as! String
    let error: String? = nilOrValue(pigeonVar_list[1])

    return InitializationResult(
      status: status,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      error,
    ]
  }
  static func == (lhs: InitializationResult, rhs: InitializationResult) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Reward data from a rewarded ad.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RewardData: Hashable {
  var type: String? = nil
  var count: Int64? = nil
  var ext: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RewardData? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let count: Int64? = nilOrValue(pigeonVar_list[1])
    let ext: [String?: Any?]? = nilOrValue(pigeonVar_list[2])

    return RewardData(
      type: type,
      count: count,
      ext: ext
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      count,
      ext,
    ]
  }
  static func == (lhs: RewardData, rhs: RewardData) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Ad event sent from native to Flutter.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AdEvent: Hashable {
  var adId: Int64
  var eventName: String
  var error: String? = nil
  var reward: RewardData? = nil
  var nativeAd: NativeAdData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdEvent? {
    let adId = pigeonVar_list[0] as! Int64
    let eventName = pigeonVar_list[1] as! String
    let error: String? = nilOrValue(pigeonVar_list[2])
    let reward: RewardData? = nilOrValue(pigeonVar_list[3])
    let nativeAd: NativeAdData? = nilOrValue(pigeonVar_list[4])

    return AdEvent(
      adId: adId,
      eventName: eventName,
      error: error,
      reward: reward,
      nativeAd: nativeAd
    )
  }
  func toList() -> [Any?] {
    return [
      adId,
      eventName,
      error,
      reward,
      nativeAd,
    ]
  }
  static func == (lhs: AdEvent, rhs: AdEvent) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for a native asset in a request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAssetConfig: Hashable {
  /// "title", "image", or "data"
  var assetType: String
  var required_: Bool
  var titleLength: Int64? = nil
  var imageType: Int64? = nil
  var imageWidth: Int64? = nil
  var imageHeight: Int64? = nil
  var imageWidthMin: Int64? = nil
  var imageHeightMin: Int64? = nil
  var dataType: Int64? = nil
  var dataLength: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAssetConfig? {
    let assetType = pigeonVar_list[0] as! String
    let required_ = pigeonVar_list[1] as! Bool
    let titleLength: Int64? = nilOrValue(pigeonVar_list[2])
    let imageType: Int64? = nilOrValue(pigeonVar_list[3])
    let imageWidth: Int64? = nilOrValue(pigeonVar_list[4])
    let imageHeight: Int64? = nilOrValue(pigeonVar_list[5])
    let imageWidthMin: Int64? = nilOrValue(pigeonVar_list[6])
    let imageHeightMin: Int64? = nilOrValue(pigeonVar_list[7])
    let dataType: Int64? = nilOrValue(pigeonVar_list[8])
    let dataLength: Int64? = nilOrValue(pigeonVar_list[9])

    return NativeAssetConfig(
      assetType: assetType,
      required_: required_,
      titleLength: titleLength,
      imageType: imageType,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      imageWidthMin: imageWidthMin,
      imageHeightMin: imageHeightMin,
      dataType: dataType,
      dataLength: dataLength
    )
  }
  func toList() -> [Any?] {
    return [
      assetType,
      required_,
      titleLength,
      imageType,
      imageWidth,
      imageHeight,
      imageWidthMin,
      imageHeightMin,
      dataType,
      dataLength,
    ]
  }
  static func == (lhs: NativeAssetConfig, rhs: NativeAssetConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for a native event tracker.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeEventTrackerConfig: Hashable {
  var eventType: Int64
  var methods: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeEventTrackerConfig? {
    let eventType = pigeonVar_list[0] as! Int64
    let methods = pigeonVar_list[1] as! [Int64]

    return NativeEventTrackerConfig(
      eventType: eventType,
      methods: methods
    )
  }
  func toList() -> [Any?] {
    return [
      eventType,
      methods,
    ]
  }
  static func == (lhs: NativeEventTrackerConfig, rhs: NativeEventTrackerConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Full configuration for a native ad request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdRequestConfig: Hashable {
  var configId: String
  var assets: [NativeAssetConfig?]? = nil
  var eventTrackers: [NativeEventTrackerConfig?]? = nil
  var context: Int64? = nil
  var contextSubType: Int64? = nil
  var placementType: Int64? = nil
  var placementCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdRequestConfig? {
    let configId = pigeonVar_list[0] as! String
    let assets: [NativeAssetConfig?]? = nilOrValue(pigeonVar_list[1])
    let eventTrackers: [NativeEventTrackerConfig?]? = nilOrValue(pigeonVar_list[2])
    let context: Int64? = nilOrValue(pigeonVar_list[3])
    let contextSubType: Int64? = nilOrValue(pigeonVar_list[4])
    let placementType: Int64? = nilOrValue(pigeonVar_list[5])
    let placementCount: Int64? = nilOrValue(pigeonVar_list[6])

    return NativeAdRequestConfig(
      configId: configId,
      assets: assets,
      eventTrackers: eventTrackers,
      context: context,
      contextSubType: contextSubType,
      placementType: placementType,
      placementCount: placementCount
    )
  }
  func toList() -> [Any?] {
    return [
      configId,
      assets,
      eventTrackers,
      context,
      contextSubType,
      placementType,
      placementCount,
    ]
  }
  static func == (lhs: NativeAdRequestConfig, rhs: NativeAdRequestConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Native ad response data sent back to Flutter.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdData: Hashable {
  var title: String? = nil
  var text: String? = nil
  var iconUrl: String? = nil
  var imageUrl: String? = nil
  var sponsoredBy: String? = nil
  var callToAction: String? = nil
  var clickUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdData? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let text: String? = nilOrValue(pigeonVar_list[1])
    let iconUrl: String? = nilOrValue(pigeonVar_list[2])
    let imageUrl: String? = nilOrValue(pigeonVar_list[3])
    let sponsoredBy: String? = nilOrValue(pigeonVar_list[4])
    let callToAction: String? = nilOrValue(pigeonVar_list[5])
    let clickUrl: String? = nilOrValue(pigeonVar_list[6])

    return NativeAdData(
      title: title,
      text: text,
      iconUrl: iconUrl,
      imageUrl: imageUrl,
      sponsoredBy: sponsoredBy,
      callToAction: callToAction,
      clickUrl: clickUrl
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      text,
      iconUrl,
      imageUrl,
      sponsoredBy,
      callToAction,
      clickUrl,
    ]
  }
  static func == (lhs: NativeAdData, rhs: NativeAdData) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// External user ID for third-party identity modules (UID2, SharedID, etc.).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ExternalUserIdData: Hashable {
  /// ID source (e.g., "uidapi.com", "sharedid.org").
  var source: String
  /// The user ID value.
  var identifier: String
  /// ID type per OpenRTB: 1=device, 2=person, 3=user, etc.
  var atype: Int64? = nil
  /// Optional extra data.
  var ext: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExternalUserIdData? {
    let source = pigeonVar_list[0] as! String
    let identifier = pigeonVar_list[1] as! String
    let atype: Int64? = nilOrValue(pigeonVar_list[2])
    let ext: [String?: Any?]? = nilOrValue(pigeonVar_list[3])

    return ExternalUserIdData(
      source: source,
      identifier: identifier,
      atype: atype,
      ext: ext
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      identifier,
      atype,
      ext,
    ]
  }
  static func == (lhs: ExternalUserIdData, rhs: ExternalUserIdData) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Video parameters configuration for OpenRTB video objects.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoParametersConfig: Hashable {
  /// Supported content MIME types (e.g., ["video/mp4"]).
  var mimes: [String]
  /// Supported VAST protocol IDs.
  var protocols: [Int64?]? = nil
  /// Playback method IDs.
  var playbackMethods: [Int64?]? = nil
  /// Placement type (1=in-stream, 2=in-banner, 3=in-article, 4=in-feed).
  var placement: Int64? = nil
  /// Maximum video duration in seconds.
  var maxDuration: Int64? = nil
  /// Minimum video duration in seconds.
  var minDuration: Int64? = nil
  /// Supported API frameworks (1=VPAID 1.0, 2=VPAID 2.0, 3=MRAID-1, etc.).
  var api: [Int64?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoParametersConfig? {
    let mimes = pigeonVar_list[0] as! [String]
    let protocols: [Int64?]? = nilOrValue(pigeonVar_list[1])
    let playbackMethods: [Int64?]? = nilOrValue(pigeonVar_list[2])
    let placement: Int64? = nilOrValue(pigeonVar_list[3])
    let maxDuration: Int64? = nilOrValue(pigeonVar_list[4])
    let minDuration: Int64? = nilOrValue(pigeonVar_list[5])
    let api: [Int64?]? = nilOrValue(pigeonVar_list[6])

    return VideoParametersConfig(
      mimes: mimes,
      protocols: protocols,
      playbackMethods: playbackMethods,
      placement: placement,
      maxDuration: maxDuration,
      minDuration: minDuration,
      api: api
    )
  }
  func toList() -> [Any?] {
    return [
      mimes,
      protocols,
      playbackMethods,
      placement,
      maxDuration,
      minDuration,
      api,
    ]
  }
  static func == (lhs: VideoParametersConfig, rhs: VideoParametersConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for a multiformat ad request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MultiformatAdRequestConfig: Hashable {
  var configId: String
  /// Banner sizes as [width, height, width, height, ...]
  var bannerSizes: [Int64?]? = nil
  var videoConfig: VideoParametersConfig? = nil
  var nativeConfig: NativeAdRequestConfig? = nil
  var isInterstitial: Bool
  var isRewarded: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MultiformatAdRequestConfig? {
    let configId = pigeonVar_list[0] as! String
    let bannerSizes: [Int64?]? = nilOrValue(pigeonVar_list[1])
    let videoConfig: VideoParametersConfig? = nilOrValue(pigeonVar_list[2])
    let nativeConfig: NativeAdRequestConfig? = nilOrValue(pigeonVar_list[3])
    let isInterstitial = pigeonVar_list[4] as! Bool
    let isRewarded = pigeonVar_list[5] as! Bool

    return MultiformatAdRequestConfig(
      configId: configId,
      bannerSizes: bannerSizes,
      videoConfig: videoConfig,
      nativeConfig: nativeConfig,
      isInterstitial: isInterstitial,
      isRewarded: isRewarded
    )
  }
  func toList() -> [Any?] {
    return [
      configId,
      bannerSizes,
      videoConfig,
      nativeConfig,
      isInterstitial,
      isRewarded,
    ]
  }
  static func == (lhs: MultiformatAdRequestConfig, rhs: MultiformatAdRequestConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Result of a multiformat bid request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MultiformatBidResult: Hashable {
  var resultCode: String
  /// "banner", "video", or "native"
  var winningFormat: String? = nil
  var targetingKeywords: [String?: String?]? = nil
  var nativeAdCacheId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MultiformatBidResult? {
    let resultCode = pigeonVar_list[0] as! String
    let winningFormat: String? = nilOrValue(pigeonVar_list[1])
    let targetingKeywords: [String?: String?]? = nilOrValue(pigeonVar_list[2])
    let nativeAdCacheId: String? = nilOrValue(pigeonVar_list[3])

    return MultiformatBidResult(
      resultCode: resultCode,
      winningFormat: winningFormat,
      targetingKeywords: targetingKeywords,
      nativeAdCacheId: nativeAdCacheId
    )
  }
  func toList() -> [Any?] {
    return [
      resultCode,
      winningFormat,
      targetingKeywords,
      nativeAdCacheId,
    ]
  }
  static func == (lhs: MultiformatBidResult, rhs: MultiformatBidResult) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for an in-stream video ad request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct InstreamVideoAdRequestConfig: Hashable {
  var configId: String
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InstreamVideoAdRequestConfig? {
    let configId = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64

    return InstreamVideoAdRequestConfig(
      configId: configId,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      configId,
      width,
      height,
    ]
  }
  static func == (lhs: InstreamVideoAdRequestConfig, rhs: InstreamVideoAdRequestConfig) -> Bool {
    return deepEqualsPrebidApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrebidApi(value: toList(), hasher: &hasher)
  }
}

private class PrebidApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitializationResult.fromList(self.readValue() as! [Any?])
    case 130:
      return RewardData.fromList(self.readValue() as! [Any?])
    case 131:
      return AdEvent.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeAssetConfig.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeEventTrackerConfig.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeAdRequestConfig.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeAdData.fromList(self.readValue() as! [Any?])
    case 136:
      return ExternalUserIdData.fromList(self.readValue() as! [Any?])
    case 137:
      return VideoParametersConfig.fromList(self.readValue() as! [Any?])
    case 138:
      return MultiformatAdRequestConfig.fromList(self.readValue() as! [Any?])
    case 139:
      return MultiformatBidResult.fromList(self.readValue() as! [Any?])
    case 140:
      return InstreamVideoAdRequestConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PrebidApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitializationResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? RewardData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AdEvent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAssetConfig {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeEventTrackerConfig {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdRequestConfig {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ExternalUserIdData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VideoParametersConfig {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? MultiformatAdRequestConfig {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? MultiformatBidResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? InstreamVideoAdRequestConfig {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PrebidApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PrebidApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PrebidApiPigeonCodecWriter(data: data)
  }
}

class PrebidApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PrebidApiPigeonCodec(readerWriter: PrebidApiPigeonCodecReaderWriter())
}


/// Core SDK initialization and configuration.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PrebidMobileHostApi {
  func initializeSdk(prebidServerUrl: String, accountId: String, completion: @escaping (Result<InitializationResult, Error>) -> Void)
  func setTimeoutMillis(timeoutMillis: Int64) throws
  func setShareGeoLocation(share: Bool) throws
  func setPbsDebug(enabled: Bool) throws
  func setCustomHeaders(headers: [String: String]) throws
  func setStoredAuctionResponse(response: String) throws
  func clearStoredAuctionResponse() throws
  func addStoredBidResponse(bidder: String, responseId: String) throws
  func clearStoredBidResponses() throws
  func setLogLevel(level: Int64) throws
  func setCreativeFactoryTimeout(timeout: Int64) throws
  func setCreativeFactoryTimeoutPreRenderContent(timeout: Int64) throws
  func setCustomStatusEndpoint(endpoint: String) throws
  func setExternalUserIds(userIds: [ExternalUserIdData]) throws
  func getExternalUserIds() throws -> [ExternalUserIdData]
  func clearExternalUserIds() throws
  func getSdkVersion() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PrebidMobileHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `PrebidMobileHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PrebidMobileHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeSdkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.initializeSdk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeSdkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let prebidServerUrlArg = args[0] as! String
        let accountIdArg = args[1] as! String
        api.initializeSdk(prebidServerUrl: prebidServerUrlArg, accountId: accountIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeSdkChannel.setMessageHandler(nil)
    }
    let setTimeoutMillisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setTimeoutMillis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTimeoutMillisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutMillisArg = args[0] as! Int64
        do {
          try api.setTimeoutMillis(timeoutMillis: timeoutMillisArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTimeoutMillisChannel.setMessageHandler(nil)
    }
    let setShareGeoLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setShareGeoLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShareGeoLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shareArg = args[0] as! Bool
        do {
          try api.setShareGeoLocation(share: shareArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShareGeoLocationChannel.setMessageHandler(nil)
    }
    let setPbsDebugChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setPbsDebug\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPbsDebugChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setPbsDebug(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPbsDebugChannel.setMessageHandler(nil)
    }
    let setCustomHeadersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCustomHeaders\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCustomHeadersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let headersArg = args[0] as! [String: String]
        do {
          try api.setCustomHeaders(headers: headersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCustomHeadersChannel.setMessageHandler(nil)
    }
    let setStoredAuctionResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setStoredAuctionResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStoredAuctionResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let responseArg = args[0] as! String
        do {
          try api.setStoredAuctionResponse(response: responseArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStoredAuctionResponseChannel.setMessageHandler(nil)
    }
    let clearStoredAuctionResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearStoredAuctionResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearStoredAuctionResponseChannel.setMessageHandler { _, reply in
        do {
          try api.clearStoredAuctionResponse()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearStoredAuctionResponseChannel.setMessageHandler(nil)
    }
    let addStoredBidResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.addStoredBidResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addStoredBidResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bidderArg = args[0] as! String
        let responseIdArg = args[1] as! String
        do {
          try api.addStoredBidResponse(bidder: bidderArg, responseId: responseIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addStoredBidResponseChannel.setMessageHandler(nil)
    }
    let clearStoredBidResponsesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearStoredBidResponses\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearStoredBidResponsesChannel.setMessageHandler { _, reply in
        do {
          try api.clearStoredBidResponses()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearStoredBidResponsesChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! Int64
        do {
          try api.setLogLevel(level: levelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
    let setCreativeFactoryTimeoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCreativeFactoryTimeout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCreativeFactoryTimeoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int64
        do {
          try api.setCreativeFactoryTimeout(timeout: timeoutArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCreativeFactoryTimeoutChannel.setMessageHandler(nil)
    }
    let setCreativeFactoryTimeoutPreRenderContentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCreativeFactoryTimeoutPreRenderContent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCreativeFactoryTimeoutPreRenderContentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutArg = args[0] as! Int64
        do {
          try api.setCreativeFactoryTimeoutPreRenderContent(timeout: timeoutArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCreativeFactoryTimeoutPreRenderContentChannel.setMessageHandler(nil)
    }
    let setCustomStatusEndpointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCustomStatusEndpoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCustomStatusEndpointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let endpointArg = args[0] as! String
        do {
          try api.setCustomStatusEndpoint(endpoint: endpointArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCustomStatusEndpointChannel.setMessageHandler(nil)
    }
    let setExternalUserIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setExternalUserIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExternalUserIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdsArg = args[0] as! [ExternalUserIdData]
        do {
          try api.setExternalUserIds(userIds: userIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExternalUserIdsChannel.setMessageHandler(nil)
    }
    let getExternalUserIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.getExternalUserIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getExternalUserIdsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getExternalUserIds()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getExternalUserIdsChannel.setMessageHandler(nil)
    }
    let clearExternalUserIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearExternalUserIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearExternalUserIdsChannel.setMessageHandler { _, reply in
        do {
          try api.clearExternalUserIds()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearExternalUserIdsChannel.setMessageHandler(nil)
    }
    let getSdkVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.getSdkVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSdkVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSdkVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSdkVersionChannel.setMessageHandler(nil)
    }
  }
}
/// Targeting and privacy settings.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TargetingHostApi {
  func setSubjectToCOPPA(value: Bool?) throws
  func getSubjectToCOPPA() throws -> Bool?
  func setSubjectToGDPR(value: Bool?) throws
  func getSubjectToGDPR() throws -> Bool?
  func setGDPRConsentString(value: String?) throws
  func getGDPRConsentString() throws -> String?
  func setPurposeConsents(value: String?) throws
  func getPurposeConsents() throws -> String?
  func getDeviceAccessConsent() throws -> Bool?
  func setUSPrivacyString(value: String?) throws
  func getUSPrivacyString() throws -> String?
  func addUserKeyword(keyword: String) throws
  func addUserKeywords(keywords: [String]) throws
  func removeUserKeyword(keyword: String) throws
  func clearUserKeywords() throws
  func getUserKeywords() throws -> [String]
  func addAppKeyword(keyword: String) throws
  func addAppKeywords(keywords: [String]) throws
  func removeAppKeyword(keyword: String) throws
  func clearAppKeywords() throws
  func addAppExtData(key: String, value: String) throws
  func updateAppExtData(key: String, value: [String]) throws
  func removeAppExtData(key: String) throws
  func clearAppExtData() throws
  func addUserExtData(key: String, value: String) throws
  func updateUserExtData(key: String, value: [String]) throws
  func removeUserExtData(key: String) throws
  func clearUserExtData() throws
  func addBidderToAccessControlList(bidderName: String) throws
  func removeBidderFromAccessControlList(bidderName: String) throws
  func clearAccessControlList() throws
  func setGlobalOrtbConfig(ortbConfig: String?) throws
  func getGlobalOrtbConfig() throws -> String?
  func setContentUrl(url: String?) throws
  func setPublisherName(name: String?) throws
  func setStoreUrl(url: String?) throws
  func setDomain(domain: String?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TargetingHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `TargetingHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TargetingHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setSubjectToCOPPAChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setSubjectToCOPPA\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSubjectToCOPPAChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg: Bool? = nilOrValue(args[0])
        do {
          try api.setSubjectToCOPPA(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSubjectToCOPPAChannel.setMessageHandler(nil)
    }
    let getSubjectToCOPPAChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getSubjectToCOPPA\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSubjectToCOPPAChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSubjectToCOPPA()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSubjectToCOPPAChannel.setMessageHandler(nil)
    }
    let setSubjectToGDPRChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setSubjectToGDPR\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSubjectToGDPRChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg: Bool? = nilOrValue(args[0])
        do {
          try api.setSubjectToGDPR(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSubjectToGDPRChannel.setMessageHandler(nil)
    }
    let getSubjectToGDPRChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getSubjectToGDPR\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSubjectToGDPRChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSubjectToGDPR()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSubjectToGDPRChannel.setMessageHandler(nil)
    }
    let setGDPRConsentStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setGDPRConsentString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGDPRConsentStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg: String? = nilOrValue(args[0])
        do {
          try api.setGDPRConsentString(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGDPRConsentStringChannel.setMessageHandler(nil)
    }
    let getGDPRConsentStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getGDPRConsentString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGDPRConsentStringChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGDPRConsentString()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGDPRConsentStringChannel.setMessageHandler(nil)
    }
    let setPurposeConsentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setPurposeConsents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPurposeConsentsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg: String? = nilOrValue(args[0])
        do {
          try api.setPurposeConsents(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPurposeConsentsChannel.setMessageHandler(nil)
    }
    let getPurposeConsentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getPurposeConsents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPurposeConsentsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPurposeConsents()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPurposeConsentsChannel.setMessageHandler(nil)
    }
    let getDeviceAccessConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getDeviceAccessConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceAccessConsentChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceAccessConsent()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceAccessConsentChannel.setMessageHandler(nil)
    }
    let setUSPrivacyStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setUSPrivacyString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUSPrivacyStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg: String? = nilOrValue(args[0])
        do {
          try api.setUSPrivacyString(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUSPrivacyStringChannel.setMessageHandler(nil)
    }
    let getUSPrivacyStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getUSPrivacyString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUSPrivacyStringChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUSPrivacyString()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUSPrivacyStringChannel.setMessageHandler(nil)
    }
    let addUserKeywordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserKeyword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addUserKeywordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordArg = args[0] as! String
        do {
          try api.addUserKeyword(keyword: keywordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addUserKeywordChannel.setMessageHandler(nil)
    }
    let addUserKeywordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserKeywords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addUserKeywordsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordsArg = args[0] as! [String]
        do {
          try api.addUserKeywords(keywords: keywordsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addUserKeywordsChannel.setMessageHandler(nil)
    }
    let removeUserKeywordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeUserKeyword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeUserKeywordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordArg = args[0] as! String
        do {
          try api.removeUserKeyword(keyword: keywordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeUserKeywordChannel.setMessageHandler(nil)
    }
    let clearUserKeywordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearUserKeywords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearUserKeywordsChannel.setMessageHandler { _, reply in
        do {
          try api.clearUserKeywords()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearUserKeywordsChannel.setMessageHandler(nil)
    }
    let getUserKeywordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getUserKeywords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserKeywordsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUserKeywords()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUserKeywordsChannel.setMessageHandler(nil)
    }
    let addAppKeywordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppKeyword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAppKeywordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordArg = args[0] as! String
        do {
          try api.addAppKeyword(keyword: keywordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAppKeywordChannel.setMessageHandler(nil)
    }
    let addAppKeywordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppKeywords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAppKeywordsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordsArg = args[0] as! [String]
        do {
          try api.addAppKeywords(keywords: keywordsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAppKeywordsChannel.setMessageHandler(nil)
    }
    let removeAppKeywordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeAppKeyword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAppKeywordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keywordArg = args[0] as! String
        do {
          try api.removeAppKeyword(keyword: keywordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeAppKeywordChannel.setMessageHandler(nil)
    }
    let clearAppKeywordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAppKeywords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAppKeywordsChannel.setMessageHandler { _, reply in
        do {
          try api.clearAppKeywords()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAppKeywordsChannel.setMessageHandler(nil)
    }
    let addAppExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAppExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          try api.addAppExtData(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAppExtDataChannel.setMessageHandler(nil)
    }
    let updateAppExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.updateAppExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAppExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! [String]
        do {
          try api.updateAppExtData(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateAppExtDataChannel.setMessageHandler(nil)
    }
    let removeAppExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeAppExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAppExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          try api.removeAppExtData(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeAppExtDataChannel.setMessageHandler(nil)
    }
    let clearAppExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAppExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAppExtDataChannel.setMessageHandler { _, reply in
        do {
          try api.clearAppExtData()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAppExtDataChannel.setMessageHandler(nil)
    }
    let addUserExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addUserExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          try api.addUserExtData(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addUserExtDataChannel.setMessageHandler(nil)
    }
    let updateUserExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.updateUserExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateUserExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! [String]
        do {
          try api.updateUserExtData(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateUserExtDataChannel.setMessageHandler(nil)
    }
    let removeUserExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeUserExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeUserExtDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          try api.removeUserExtData(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeUserExtDataChannel.setMessageHandler(nil)
    }
    let clearUserExtDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearUserExtData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearUserExtDataChannel.setMessageHandler { _, reply in
        do {
          try api.clearUserExtData()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearUserExtDataChannel.setMessageHandler(nil)
    }
    let addBidderToAccessControlListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addBidderToAccessControlList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addBidderToAccessControlListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bidderNameArg = args[0] as! String
        do {
          try api.addBidderToAccessControlList(bidderName: bidderNameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addBidderToAccessControlListChannel.setMessageHandler(nil)
    }
    let removeBidderFromAccessControlListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeBidderFromAccessControlList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeBidderFromAccessControlListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bidderNameArg = args[0] as! String
        do {
          try api.removeBidderFromAccessControlList(bidderName: bidderNameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeBidderFromAccessControlListChannel.setMessageHandler(nil)
    }
    let clearAccessControlListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAccessControlList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAccessControlListChannel.setMessageHandler { _, reply in
        do {
          try api.clearAccessControlList()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAccessControlListChannel.setMessageHandler(nil)
    }
    let setGlobalOrtbConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setGlobalOrtbConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGlobalOrtbConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ortbConfigArg: String? = nilOrValue(args[0])
        do {
          try api.setGlobalOrtbConfig(ortbConfig: ortbConfigArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGlobalOrtbConfigChannel.setMessageHandler(nil)
    }
    let getGlobalOrtbConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getGlobalOrtbConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGlobalOrtbConfigChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGlobalOrtbConfig()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGlobalOrtbConfigChannel.setMessageHandler(nil)
    }
    let setContentUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setContentUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setContentUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg: String? = nilOrValue(args[0])
        do {
          try api.setContentUrl(url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setContentUrlChannel.setMessageHandler(nil)
    }
    let setPublisherNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setPublisherName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPublisherNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        do {
          try api.setPublisherName(name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPublisherNameChannel.setMessageHandler(nil)
    }
    let setStoreUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setStoreUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStoreUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg: String? = nilOrValue(args[0])
        do {
          try api.setStoreUrl(url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStoreUrlChannel.setMessageHandler(nil)
    }
    let setDomainChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setDomain\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDomainChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let domainArg: String? = nilOrValue(args[0])
        do {
          try api.setDomain(domain: domainArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDomainChannel.setMessageHandler(nil)
    }
  }
}
/// Interstitial ad operations (Dart → Native).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InterstitialAdHostApi {
  func loadAd(adId: Int64, configId: String, adFormats: [String]?, videoConfig: VideoParametersConfig?) throws
  func show(adId: Int64) throws
  func destroy(adId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InterstitialAdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `InterstitialAdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InterstitialAdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.loadAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        let configIdArg = args[1] as! String
        let adFormatsArg: [String]? = nilOrValue(args[2])
        let videoConfigArg: VideoParametersConfig? = nilOrValue(args[3])
        do {
          try api.loadAd(adId: adIdArg, configId: configIdArg, adFormats: adFormatsArg, videoConfig: videoConfigArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadAdChannel.setMessageHandler(nil)
    }
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.show(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
/// Rewarded ad operations (Dart → Native).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RewardedAdHostApi {
  func loadAd(adId: Int64, configId: String) throws
  func show(adId: Int64) throws
  func destroy(adId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RewardedAdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `RewardedAdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RewardedAdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.loadAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        let configIdArg = args[1] as! String
        do {
          try api.loadAd(adId: adIdArg, configId: configIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadAdChannel.setMessageHandler(nil)
    }
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.show(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
/// Native ad operations (Dart → Native).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeAdHostApi {
  func loadAd(adId: Int64, config: NativeAdRequestConfig) throws
  func trackImpression(adId: Int64) throws
  func trackClick(adId: Int64) throws
  func destroy(adId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeAdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `NativeAdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeAdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.loadAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        let configArg = args[1] as! NativeAdRequestConfig
        do {
          try api.loadAd(adId: adIdArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadAdChannel.setMessageHandler(nil)
    }
    let trackImpressionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.trackImpression\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackImpressionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.trackImpression(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackImpressionChannel.setMessageHandler(nil)
    }
    let trackClickChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.trackClick\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackClickChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.trackClick(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackClickChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
/// Multiformat ad operations (Dart → Native).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MultiformatAdHostApi {
  func fetchDemand(adId: Int64, config: MultiformatAdRequestConfig, completion: @escaping (Result<MultiformatBidResult, Error>) -> Void)
  func destroy(adId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MultiformatAdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `MultiformatAdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MultiformatAdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let fetchDemandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.MultiformatAdHostApi.fetchDemand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchDemandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        let configArg = args[1] as! MultiformatAdRequestConfig
        api.fetchDemand(adId: adIdArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchDemandChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.MultiformatAdHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
/// In-stream video ad operations (Dart → Native).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InstreamVideoAdHostApi {
  func fetchDemand(adId: Int64, config: InstreamVideoAdRequestConfig, completion: @escaping (Result<MultiformatBidResult, Error>) -> Void)
  func destroy(adId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InstreamVideoAdHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrebidApiPigeonCodec.shared }
  /// Sets up an instance of `InstreamVideoAdHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InstreamVideoAdHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let fetchDemandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.InstreamVideoAdHostApi.fetchDemand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchDemandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        let configArg = args[1] as! InstreamVideoAdRequestConfig
        api.fetchDemand(adId: adIdArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchDemandChannel.setMessageHandler(nil)
    }
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.prebid_mobile_sdk.InstreamVideoAdHostApi.destroy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let adIdArg = args[0] as! Int64
        do {
          try api.destroy(adId: adIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
/// Callbacks for ad events from native to Flutter.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AdFlutterApiProtocol {
  func onAdEvent(event eventArg: AdEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AdFlutterApi: AdFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PrebidApiPigeonCodec {
    return PrebidApiPigeonCodec.shared
  }
  func onAdEvent(event eventArg: AdEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.prebid_mobile_sdk.AdFlutterApi.onAdEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
