// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.prebid.prebid_mobile_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrebidApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Result of SDK initialization.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitializationResult (
  val status: String,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializationResult {
      val status = pigeonVar_list[0] as String
      val error = pigeonVar_list[1] as String?
      return InitializationResult(status, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InitializationResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Reward data from a rewarded ad.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RewardData (
  val type: String? = null,
  val count: Long? = null,
  val ext: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RewardData {
      val type = pigeonVar_list[0] as String?
      val count = pigeonVar_list[1] as Long?
      val ext = pigeonVar_list[2] as Map<String?, Any?>?
      return RewardData(type, count, ext)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      count,
      ext,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RewardData) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Ad event sent from native to Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AdEvent (
  val adId: Long,
  val eventName: String,
  val error: String? = null,
  val reward: RewardData? = null,
  val nativeAd: NativeAdData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdEvent {
      val adId = pigeonVar_list[0] as Long
      val eventName = pigeonVar_list[1] as String
      val error = pigeonVar_list[2] as String?
      val reward = pigeonVar_list[3] as RewardData?
      val nativeAd = pigeonVar_list[4] as NativeAdData?
      return AdEvent(adId, eventName, error, reward, nativeAd)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      adId,
      eventName,
      error,
      reward,
      nativeAd,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AdEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for a native asset in a request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAssetConfig (
  /** "title", "image", or "data" */
  val assetType: String,
  val required_: Boolean,
  val titleLength: Long? = null,
  val imageType: Long? = null,
  val imageWidth: Long? = null,
  val imageHeight: Long? = null,
  val imageWidthMin: Long? = null,
  val imageHeightMin: Long? = null,
  val dataType: Long? = null,
  val dataLength: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAssetConfig {
      val assetType = pigeonVar_list[0] as String
      val required_ = pigeonVar_list[1] as Boolean
      val titleLength = pigeonVar_list[2] as Long?
      val imageType = pigeonVar_list[3] as Long?
      val imageWidth = pigeonVar_list[4] as Long?
      val imageHeight = pigeonVar_list[5] as Long?
      val imageWidthMin = pigeonVar_list[6] as Long?
      val imageHeightMin = pigeonVar_list[7] as Long?
      val dataType = pigeonVar_list[8] as Long?
      val dataLength = pigeonVar_list[9] as Long?
      return NativeAssetConfig(assetType, required_, titleLength, imageType, imageWidth, imageHeight, imageWidthMin, imageHeightMin, dataType, dataLength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      assetType,
      required_,
      titleLength,
      imageType,
      imageWidth,
      imageHeight,
      imageWidthMin,
      imageHeightMin,
      dataType,
      dataLength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeAssetConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for a native event tracker.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeEventTrackerConfig (
  val eventType: Long,
  val methods: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeEventTrackerConfig {
      val eventType = pigeonVar_list[0] as Long
      val methods = pigeonVar_list[1] as List<Long>
      return NativeEventTrackerConfig(eventType, methods)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventType,
      methods,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeEventTrackerConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Full configuration for a native ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAdRequestConfig (
  val configId: String,
  val assets: List<NativeAssetConfig?>? = null,
  val eventTrackers: List<NativeEventTrackerConfig?>? = null,
  val context: Long? = null,
  val contextSubType: Long? = null,
  val placementType: Long? = null,
  val placementCount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val assets = pigeonVar_list[1] as List<NativeAssetConfig?>?
      val eventTrackers = pigeonVar_list[2] as List<NativeEventTrackerConfig?>?
      val context = pigeonVar_list[3] as Long?
      val contextSubType = pigeonVar_list[4] as Long?
      val placementType = pigeonVar_list[5] as Long?
      val placementCount = pigeonVar_list[6] as Long?
      return NativeAdRequestConfig(configId, assets, eventTrackers, context, contextSubType, placementType, placementCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      assets,
      eventTrackers,
      context,
      contextSubType,
      placementType,
      placementCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeAdRequestConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Native ad response data sent back to Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAdData (
  val title: String? = null,
  val text: String? = null,
  val iconUrl: String? = null,
  val imageUrl: String? = null,
  val sponsoredBy: String? = null,
  val callToAction: String? = null,
  val clickUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdData {
      val title = pigeonVar_list[0] as String?
      val text = pigeonVar_list[1] as String?
      val iconUrl = pigeonVar_list[2] as String?
      val imageUrl = pigeonVar_list[3] as String?
      val sponsoredBy = pigeonVar_list[4] as String?
      val callToAction = pigeonVar_list[5] as String?
      val clickUrl = pigeonVar_list[6] as String?
      return NativeAdData(title, text, iconUrl, imageUrl, sponsoredBy, callToAction, clickUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      text,
      iconUrl,
      imageUrl,
      sponsoredBy,
      callToAction,
      clickUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeAdData) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for a multiformat ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MultiformatAdRequestConfig (
  val configId: String,
  /** Banner sizes as [width, height, width, height, ...] */
  val bannerSizes: List<Long?>? = null,
  val includeVideo: Boolean,
  val nativeConfig: NativeAdRequestConfig? = null,
  val isInterstitial: Boolean,
  val isRewarded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MultiformatAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val bannerSizes = pigeonVar_list[1] as List<Long?>?
      val includeVideo = pigeonVar_list[2] as Boolean
      val nativeConfig = pigeonVar_list[3] as NativeAdRequestConfig?
      val isInterstitial = pigeonVar_list[4] as Boolean
      val isRewarded = pigeonVar_list[5] as Boolean
      return MultiformatAdRequestConfig(configId, bannerSizes, includeVideo, nativeConfig, isInterstitial, isRewarded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      bannerSizes,
      includeVideo,
      nativeConfig,
      isInterstitial,
      isRewarded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MultiformatAdRequestConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of a multiformat bid request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MultiformatBidResult (
  val resultCode: String,
  /** "banner", "video", or "native" */
  val winningFormat: String? = null,
  val targetingKeywords: Map<String?, String?>? = null,
  val nativeAdCacheId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MultiformatBidResult {
      val resultCode = pigeonVar_list[0] as String
      val winningFormat = pigeonVar_list[1] as String?
      val targetingKeywords = pigeonVar_list[2] as Map<String?, String?>?
      val nativeAdCacheId = pigeonVar_list[3] as String?
      return MultiformatBidResult(resultCode, winningFormat, targetingKeywords, nativeAdCacheId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resultCode,
      winningFormat,
      targetingKeywords,
      nativeAdCacheId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MultiformatBidResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for an in-stream video ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InstreamVideoAdRequestConfig (
  val configId: String,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstreamVideoAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return InstreamVideoAdRequestConfig(configId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InstreamVideoAdRequestConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrebidApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PrebidApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializationResult.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RewardData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdEvent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAssetConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeEventTrackerConfig.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdRequestConfig.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdData.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MultiformatAdRequestConfig.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MultiformatBidResult.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstreamVideoAdRequestConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitializationResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RewardData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AdEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAssetConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeEventTrackerConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeAdRequestConfig -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeAdData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is MultiformatAdRequestConfig -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is MultiformatBidResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is InstreamVideoAdRequestConfig -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Core SDK initialization and configuration.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PrebidMobileHostApi {
  fun initializeSdk(prebidServerUrl: String, accountId: String, callback: (Result<InitializationResult>) -> Unit)
  fun setTimeoutMillis(timeoutMillis: Long)
  fun setShareGeoLocation(share: Boolean)
  fun setPbsDebug(enabled: Boolean)
  fun setCustomHeaders(headers: Map<String, String>)
  fun setStoredAuctionResponse(response: String)
  fun clearStoredAuctionResponse()
  fun addStoredBidResponse(bidder: String, responseId: String)
  fun clearStoredBidResponses()
  fun setLogLevel(level: Long)
  fun setCreativeFactoryTimeout(timeout: Long)
  fun setCreativeFactoryTimeoutPreRenderContent(timeout: Long)
  fun setCustomStatusEndpoint(endpoint: String)

  companion object {
    /** The codec used by PrebidMobileHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `PrebidMobileHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PrebidMobileHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.initializeSdk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prebidServerUrlArg = args[0] as String
            val accountIdArg = args[1] as String
            api.initializeSdk(prebidServerUrlArg, accountIdArg) { result: Result<InitializationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setTimeoutMillis$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutMillisArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setTimeoutMillis(timeoutMillisArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setShareGeoLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shareArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShareGeoLocation(shareArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setPbsDebug$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setPbsDebug(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setCustomHeaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headersArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.setCustomHeaders(headersArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setStoredAuctionResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val responseArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setStoredAuctionResponse(responseArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.clearStoredAuctionResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearStoredAuctionResponse()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.addStoredBidResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderArg = args[0] as String
            val responseIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addStoredBidResponse(bidderArg, responseIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.clearStoredBidResponses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearStoredBidResponses()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setLogLevel(levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setCreativeFactoryTimeout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setCreativeFactoryTimeout(timeoutArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setCreativeFactoryTimeoutPreRenderContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setCreativeFactoryTimeoutPreRenderContent(timeoutArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.PrebidMobileHostApi.setCustomStatusEndpoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val endpointArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setCustomStatusEndpoint(endpointArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Targeting and privacy settings.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TargetingHostApi {
  fun setSubjectToCOPPA(value: Boolean?)
  fun getSubjectToCOPPA(): Boolean?
  fun setSubjectToGDPR(value: Boolean?)
  fun getSubjectToGDPR(): Boolean?
  fun setGDPRConsentString(value: String?)
  fun getGDPRConsentString(): String?
  fun setPurposeConsents(value: String?)
  fun getPurposeConsents(): String?
  fun getDeviceAccessConsent(): Boolean?
  fun addUserKeyword(keyword: String)
  fun addUserKeywords(keywords: List<String>)
  fun removeUserKeyword(keyword: String)
  fun clearUserKeywords()
  fun getUserKeywords(): List<String>
  fun addAppKeyword(keyword: String)
  fun addAppKeywords(keywords: List<String>)
  fun removeAppKeyword(keyword: String)
  fun clearAppKeywords()
  fun addAppExtData(key: String, value: String)
  fun updateAppExtData(key: String, value: List<String>)
  fun removeAppExtData(key: String)
  fun clearAppExtData()
  fun addBidderToAccessControlList(bidderName: String)
  fun removeBidderFromAccessControlList(bidderName: String)
  fun clearAccessControlList()
  fun setGlobalOrtbConfig(ortbConfig: String?)
  fun getGlobalOrtbConfig(): String?
  fun setContentUrl(url: String?)
  fun setPublisherName(name: String?)
  fun setStoreUrl(url: String?)
  fun setDomain(domain: String?)

  companion object {
    /** The codec used by TargetingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `TargetingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TargetingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setSubjectToCOPPA$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean?
            val wrapped: List<Any?> = try {
              api.setSubjectToCOPPA(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getSubjectToCOPPA$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSubjectToCOPPA())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setSubjectToGDPR$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean?
            val wrapped: List<Any?> = try {
              api.setSubjectToGDPR(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getSubjectToGDPR$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSubjectToGDPR())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setGDPRConsentString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setGDPRConsentString(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getGDPRConsentString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGDPRConsentString())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setPurposeConsents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setPurposeConsents(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getPurposeConsents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPurposeConsents())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getDeviceAccessConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceAccessConsent())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addUserKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addUserKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.addUserKeywords(keywordsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.removeUserKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeUserKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.clearUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearUserKeywords()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUserKeywords())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addAppKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addAppKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addAppKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.addAppKeywords(keywordsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.removeAppKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeAppKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.clearAppKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAppKeywords()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addAppExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.updateAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.updateAppExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.removeAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeAppExtData(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.clearAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAppExtData()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.addBidderToAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addBidderToAccessControlList(bidderNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.removeBidderFromAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeBidderFromAccessControlList(bidderNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.clearAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAccessControlList()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setGlobalOrtbConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ortbConfigArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setGlobalOrtbConfig(ortbConfigArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.getGlobalOrtbConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGlobalOrtbConfig())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setContentUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setContentUrl(urlArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setPublisherName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setPublisherName(nameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setStoreUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setStoreUrl(urlArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.TargetingHostApi.setDomain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val domainArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setDomain(domainArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Interstitial ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InterstitialAdHostApi {
  fun loadAd(adId: Long, configId: String, adFormats: List<String>?)
  fun show(adId: Long)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by InterstitialAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `InterstitialAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InterstitialAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.InterstitialAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configIdArg = args[1] as String
            val adFormatsArg = args[2] as List<String>?
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configIdArg, adFormatsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.InterstitialAdHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.show(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.InterstitialAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Rewarded ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface RewardedAdHostApi {
  fun loadAd(adId: Long, configId: String)
  fun show(adId: Long)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by RewardedAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `RewardedAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RewardedAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.RewardedAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.RewardedAdHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.show(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.RewardedAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeAdHostApi {
  fun loadAd(adId: Long, config: NativeAdRequestConfig)
  fun trackImpression(adId: Long)
  fun trackClick(adId: Long)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by NativeAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `NativeAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.NativeAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as NativeAdRequestConfig
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.NativeAdHostApi.trackImpression$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.trackImpression(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.NativeAdHostApi.trackClick$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.trackClick(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.NativeAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Multiformat ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MultiformatAdHostApi {
  fun fetchDemand(adId: Long, config: MultiformatAdRequestConfig, callback: (Result<MultiformatBidResult>) -> Unit)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by MultiformatAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `MultiformatAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MultiformatAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.MultiformatAdHostApi.fetchDemand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as MultiformatAdRequestConfig
            api.fetchDemand(adIdArg, configArg) { result: Result<MultiformatBidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.MultiformatAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * In-stream video ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InstreamVideoAdHostApi {
  fun fetchDemand(adId: Long, config: InstreamVideoAdRequestConfig, callback: (Result<MultiformatBidResult>) -> Unit)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by InstreamVideoAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `InstreamVideoAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InstreamVideoAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.InstreamVideoAdHostApi.fetchDemand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as InstreamVideoAdRequestConfig
            api.fetchDemand(adIdArg, configArg) { result: Result<MultiformatBidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_flutter.InstreamVideoAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Callbacks for ad events from native to Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class AdFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AdFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
  }
  fun onAdEvent(eventArg: AdEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.prebid_mobile_flutter.AdFlutterApi.onAdEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrebidApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
