// swift-tools-version: 5.9
import PackageDescription

let package = Package(
  name: "prebid_mobile_sdk_admob",
  platforms: [
    .iOS("15.0")
  ],
  products: [
    .library(name: "prebid-mobile-sdk-admob", targets: ["prebid_mobile_sdk_admob"])
  ],
  dependencies: [
    // Generated by the Flutter tool (Flutter 3.44+, as the plugin template).
    .package(name: "FlutterFramework", path: "../FlutterFramework"),
    .package(url: "https://github.com/prebid/prebid-mobile-ios.git", from: "3.4.1"),
    .package(
      url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
      from: "13.0.0"
    ),
  ],
  targets: [
    .target(
      name: "prebid_mobile_sdk_admob",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
        .product(name: "PrebidMobile", package: "prebid-mobile-ios"),
        .product(name: "PrebidMobileAdMobAdapters", package: "prebid-mobile-ios"),
        .product(
          name: "GoogleMobileAds",
          package: "swift-package-manager-google-mobile-ads"
        ),
      ]
    )
  ]
)
