// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.prebid.prebid_mobile_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrebidApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Result of SDK initialization.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitializationResult (
  val status: String,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializationResult {
      val status = pigeonVar_list[0] as String
      val error = pigeonVar_list[1] as String?
      return InitializationResult(status, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InitializationResult
    return PrebidApiPigeonUtils.deepEquals(this.status, other.status) && PrebidApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.status)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.error)
    return result
  }
}

/**
 * Reward data from a rewarded ad.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RewardData (
  val type: String? = null,
  val count: Long? = null,
  val ext: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RewardData {
      val type = pigeonVar_list[0] as String?
      val count = pigeonVar_list[1] as Long?
      val ext = pigeonVar_list[2] as Map<String?, Any?>?
      return RewardData(type, count, ext)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      count,
      ext,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RewardData
    return PrebidApiPigeonUtils.deepEquals(this.type, other.type) && PrebidApiPigeonUtils.deepEquals(this.count, other.count) && PrebidApiPigeonUtils.deepEquals(this.ext, other.ext)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.type)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.count)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.ext)
    return result
  }
}

/**
 * Ad event sent from native to Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AdEvent (
  val adId: Long,
  val eventName: String,
  val error: String? = null,
  val reward: RewardData? = null,
  val nativeAd: NativeAdData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdEvent {
      val adId = pigeonVar_list[0] as Long
      val eventName = pigeonVar_list[1] as String
      val error = pigeonVar_list[2] as String?
      val reward = pigeonVar_list[3] as RewardData?
      val nativeAd = pigeonVar_list[4] as NativeAdData?
      return AdEvent(adId, eventName, error, reward, nativeAd)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      adId,
      eventName,
      error,
      reward,
      nativeAd,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AdEvent
    return PrebidApiPigeonUtils.deepEquals(this.adId, other.adId) && PrebidApiPigeonUtils.deepEquals(this.eventName, other.eventName) && PrebidApiPigeonUtils.deepEquals(this.error, other.error) && PrebidApiPigeonUtils.deepEquals(this.reward, other.reward) && PrebidApiPigeonUtils.deepEquals(this.nativeAd, other.nativeAd)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.adId)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.eventName)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.error)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.reward)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.nativeAd)
    return result
  }
}

/**
 * Configuration for a native asset in a request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAssetConfig (
  /** "title", "image", or "data" */
  val assetType: String,
  val required_: Boolean,
  val titleLength: Long? = null,
  val imageType: Long? = null,
  val imageWidth: Long? = null,
  val imageHeight: Long? = null,
  val imageWidthMin: Long? = null,
  val imageHeightMin: Long? = null,
  val dataType: Long? = null,
  val dataLength: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAssetConfig {
      val assetType = pigeonVar_list[0] as String
      val required_ = pigeonVar_list[1] as Boolean
      val titleLength = pigeonVar_list[2] as Long?
      val imageType = pigeonVar_list[3] as Long?
      val imageWidth = pigeonVar_list[4] as Long?
      val imageHeight = pigeonVar_list[5] as Long?
      val imageWidthMin = pigeonVar_list[6] as Long?
      val imageHeightMin = pigeonVar_list[7] as Long?
      val dataType = pigeonVar_list[8] as Long?
      val dataLength = pigeonVar_list[9] as Long?
      return NativeAssetConfig(assetType, required_, titleLength, imageType, imageWidth, imageHeight, imageWidthMin, imageHeightMin, dataType, dataLength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      assetType,
      required_,
      titleLength,
      imageType,
      imageWidth,
      imageHeight,
      imageWidthMin,
      imageHeightMin,
      dataType,
      dataLength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAssetConfig
    return PrebidApiPigeonUtils.deepEquals(this.assetType, other.assetType) && PrebidApiPigeonUtils.deepEquals(this.required_, other.required_) && PrebidApiPigeonUtils.deepEquals(this.titleLength, other.titleLength) && PrebidApiPigeonUtils.deepEquals(this.imageType, other.imageType) && PrebidApiPigeonUtils.deepEquals(this.imageWidth, other.imageWidth) && PrebidApiPigeonUtils.deepEquals(this.imageHeight, other.imageHeight) && PrebidApiPigeonUtils.deepEquals(this.imageWidthMin, other.imageWidthMin) && PrebidApiPigeonUtils.deepEquals(this.imageHeightMin, other.imageHeightMin) && PrebidApiPigeonUtils.deepEquals(this.dataType, other.dataType) && PrebidApiPigeonUtils.deepEquals(this.dataLength, other.dataLength)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.assetType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.required_)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.titleLength)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageWidth)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageHeight)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageWidthMin)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageHeightMin)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.dataType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.dataLength)
    return result
  }
}

/**
 * Configuration for a native event tracker.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeEventTrackerConfig (
  val eventType: Long,
  val methods: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeEventTrackerConfig {
      val eventType = pigeonVar_list[0] as Long
      val methods = pigeonVar_list[1] as List<Long>
      return NativeEventTrackerConfig(eventType, methods)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventType,
      methods,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeEventTrackerConfig
    return PrebidApiPigeonUtils.deepEquals(this.eventType, other.eventType) && PrebidApiPigeonUtils.deepEquals(this.methods, other.methods)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.eventType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.methods)
    return result
  }
}

/**
 * Full configuration for a native ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAdRequestConfig (
  val configId: String,
  val assets: List<NativeAssetConfig?>? = null,
  val eventTrackers: List<NativeEventTrackerConfig?>? = null,
  val context: Long? = null,
  val contextSubType: Long? = null,
  val placementType: Long? = null,
  val placementCount: Long? = null,
  val pbAdSlot: String? = null,
  val gpid: String? = null,
  val impOrtbConfig: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val assets = pigeonVar_list[1] as List<NativeAssetConfig?>?
      val eventTrackers = pigeonVar_list[2] as List<NativeEventTrackerConfig?>?
      val context = pigeonVar_list[3] as Long?
      val contextSubType = pigeonVar_list[4] as Long?
      val placementType = pigeonVar_list[5] as Long?
      val placementCount = pigeonVar_list[6] as Long?
      val pbAdSlot = pigeonVar_list[7] as String?
      val gpid = pigeonVar_list[8] as String?
      val impOrtbConfig = pigeonVar_list[9] as String?
      return NativeAdRequestConfig(configId, assets, eventTrackers, context, contextSubType, placementType, placementCount, pbAdSlot, gpid, impOrtbConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      assets,
      eventTrackers,
      context,
      contextSubType,
      placementType,
      placementCount,
      pbAdSlot,
      gpid,
      impOrtbConfig,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAdRequestConfig
    return PrebidApiPigeonUtils.deepEquals(this.configId, other.configId) && PrebidApiPigeonUtils.deepEquals(this.assets, other.assets) && PrebidApiPigeonUtils.deepEquals(this.eventTrackers, other.eventTrackers) && PrebidApiPigeonUtils.deepEquals(this.context, other.context) && PrebidApiPigeonUtils.deepEquals(this.contextSubType, other.contextSubType) && PrebidApiPigeonUtils.deepEquals(this.placementType, other.placementType) && PrebidApiPigeonUtils.deepEquals(this.placementCount, other.placementCount) && PrebidApiPigeonUtils.deepEquals(this.pbAdSlot, other.pbAdSlot) && PrebidApiPigeonUtils.deepEquals(this.gpid, other.gpid) && PrebidApiPigeonUtils.deepEquals(this.impOrtbConfig, other.impOrtbConfig)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.configId)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.assets)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.eventTrackers)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.context)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.contextSubType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.placementType)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.placementCount)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.pbAdSlot)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.gpid)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.impOrtbConfig)
    return result
  }
}

/**
 * Native ad response data sent back to Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAdData (
  val title: String? = null,
  val text: String? = null,
  val iconUrl: String? = null,
  val imageUrl: String? = null,
  val sponsoredBy: String? = null,
  val callToAction: String? = null,
  val clickUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdData {
      val title = pigeonVar_list[0] as String?
      val text = pigeonVar_list[1] as String?
      val iconUrl = pigeonVar_list[2] as String?
      val imageUrl = pigeonVar_list[3] as String?
      val sponsoredBy = pigeonVar_list[4] as String?
      val callToAction = pigeonVar_list[5] as String?
      val clickUrl = pigeonVar_list[6] as String?
      return NativeAdData(title, text, iconUrl, imageUrl, sponsoredBy, callToAction, clickUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      text,
      iconUrl,
      imageUrl,
      sponsoredBy,
      callToAction,
      clickUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAdData
    return PrebidApiPigeonUtils.deepEquals(this.title, other.title) && PrebidApiPigeonUtils.deepEquals(this.text, other.text) && PrebidApiPigeonUtils.deepEquals(this.iconUrl, other.iconUrl) && PrebidApiPigeonUtils.deepEquals(this.imageUrl, other.imageUrl) && PrebidApiPigeonUtils.deepEquals(this.sponsoredBy, other.sponsoredBy) && PrebidApiPigeonUtils.deepEquals(this.callToAction, other.callToAction) && PrebidApiPigeonUtils.deepEquals(this.clickUrl, other.clickUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.title)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.text)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.iconUrl)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.imageUrl)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.sponsoredBy)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.callToAction)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.clickUrl)
    return result
  }
}

/**
 * External user ID for third-party identity modules (UID2, SharedID, etc.).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExternalUserIdData (
  /** OpenRTB 2.6 EID `inserter` (who inserted the ID). */
  val inserter: String? = null,
  /** OpenRTB 2.6 EID `matcher` (who matched the ID). */
  val matcher: String? = null,
  /** OpenRTB 2.6 EID `mm` (match method). */
  val mm: Long? = null,
  /** ID source (e.g., "uidapi.com", "sharedid.org"). */
  val source: String,
  /** The user ID value. */
  val identifier: String,
  /** ID type per OpenRTB: 1=device, 2=person, 3=user, etc. */
  val atype: Long? = null,
  /** Optional extra data. */
  val ext: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExternalUserIdData {
      val inserter = pigeonVar_list[0] as String?
      val matcher = pigeonVar_list[1] as String?
      val mm = pigeonVar_list[2] as Long?
      val source = pigeonVar_list[3] as String
      val identifier = pigeonVar_list[4] as String
      val atype = pigeonVar_list[5] as Long?
      val ext = pigeonVar_list[6] as Map<String?, Any?>?
      return ExternalUserIdData(inserter, matcher, mm, source, identifier, atype, ext)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inserter,
      matcher,
      mm,
      source,
      identifier,
      atype,
      ext,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExternalUserIdData
    return PrebidApiPigeonUtils.deepEquals(this.inserter, other.inserter) && PrebidApiPigeonUtils.deepEquals(this.matcher, other.matcher) && PrebidApiPigeonUtils.deepEquals(this.mm, other.mm) && PrebidApiPigeonUtils.deepEquals(this.source, other.source) && PrebidApiPigeonUtils.deepEquals(this.identifier, other.identifier) && PrebidApiPigeonUtils.deepEquals(this.atype, other.atype) && PrebidApiPigeonUtils.deepEquals(this.ext, other.ext)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.inserter)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.matcher)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.mm)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.source)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.identifier)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.atype)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.ext)
    return result
  }
}

/**
 * Video parameters configuration for OpenRTB video objects.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoParametersConfig (
  /** Supported content MIME types (e.g., ["video/mp4"]). */
  val mimes: List<String>,
  /** Supported VAST protocol IDs. */
  val protocols: List<Long?>? = null,
  /** Playback method IDs. */
  val playbackMethods: List<Long?>? = null,
  /** Placement type (1=in-stream, 2=in-banner, 3=in-article, 4=in-feed). */
  val placement: Long? = null,
  /** Maximum video duration in seconds. */
  val maxDuration: Long? = null,
  /** Minimum video duration in seconds. */
  val minDuration: Long? = null,
  /** Supported API frameworks (1=VPAID 1.0, 2=VPAID 2.0, 3=MRAID-1, etc.). */
  val api: List<Long?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoParametersConfig {
      val mimes = pigeonVar_list[0] as List<String>
      val protocols = pigeonVar_list[1] as List<Long?>?
      val playbackMethods = pigeonVar_list[2] as List<Long?>?
      val placement = pigeonVar_list[3] as Long?
      val maxDuration = pigeonVar_list[4] as Long?
      val minDuration = pigeonVar_list[5] as Long?
      val api = pigeonVar_list[6] as List<Long?>?
      return VideoParametersConfig(mimes, protocols, playbackMethods, placement, maxDuration, minDuration, api)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mimes,
      protocols,
      playbackMethods,
      placement,
      maxDuration,
      minDuration,
      api,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoParametersConfig
    return PrebidApiPigeonUtils.deepEquals(this.mimes, other.mimes) && PrebidApiPigeonUtils.deepEquals(this.protocols, other.protocols) && PrebidApiPigeonUtils.deepEquals(this.playbackMethods, other.playbackMethods) && PrebidApiPigeonUtils.deepEquals(this.placement, other.placement) && PrebidApiPigeonUtils.deepEquals(this.maxDuration, other.maxDuration) && PrebidApiPigeonUtils.deepEquals(this.minDuration, other.minDuration) && PrebidApiPigeonUtils.deepEquals(this.api, other.api)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.mimes)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.protocols)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.playbackMethods)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.placement)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.maxDuration)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.minDuration)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.api)
    return result
  }
}

/**
 * Configuration for a multiformat ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MultiformatAdRequestConfig (
  val configId: String,
  val gpid: String? = null,
  /** Banner sizes as [width, height, width, height, ...] */
  val bannerSizes: List<Long?>? = null,
  val videoConfig: VideoParametersConfig? = null,
  val nativeConfig: NativeAdRequestConfig? = null,
  val isInterstitial: Boolean,
  val isRewarded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MultiformatAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val gpid = pigeonVar_list[1] as String?
      val bannerSizes = pigeonVar_list[2] as List<Long?>?
      val videoConfig = pigeonVar_list[3] as VideoParametersConfig?
      val nativeConfig = pigeonVar_list[4] as NativeAdRequestConfig?
      val isInterstitial = pigeonVar_list[5] as Boolean
      val isRewarded = pigeonVar_list[6] as Boolean
      return MultiformatAdRequestConfig(configId, gpid, bannerSizes, videoConfig, nativeConfig, isInterstitial, isRewarded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      gpid,
      bannerSizes,
      videoConfig,
      nativeConfig,
      isInterstitial,
      isRewarded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MultiformatAdRequestConfig
    return PrebidApiPigeonUtils.deepEquals(this.configId, other.configId) && PrebidApiPigeonUtils.deepEquals(this.gpid, other.gpid) && PrebidApiPigeonUtils.deepEquals(this.bannerSizes, other.bannerSizes) && PrebidApiPigeonUtils.deepEquals(this.videoConfig, other.videoConfig) && PrebidApiPigeonUtils.deepEquals(this.nativeConfig, other.nativeConfig) && PrebidApiPigeonUtils.deepEquals(this.isInterstitial, other.isInterstitial) && PrebidApiPigeonUtils.deepEquals(this.isRewarded, other.isRewarded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.configId)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.gpid)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.bannerSizes)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.videoConfig)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.nativeConfig)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.isInterstitial)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.isRewarded)
    return result
  }
}

/**
 * Result of a multiformat bid request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MultiformatBidResult (
  val resultCode: String,
  /** Winning bid expiration in seconds (`bid.exp`), if provided. */
  val exp: Double? = null,
  /**
   * True when the top bid was dropped for a failed Prebid Cache entry and the
   * next cached bid was promoted (`filterOutUncachedBids`).
   */
  val topBidFiltered: Boolean? = null,
  /** "banner", "video", or "native" */
  val winningFormat: String? = null,
  val targetingKeywords: Map<String?, String?>? = null,
  val nativeAdCacheId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MultiformatBidResult {
      val resultCode = pigeonVar_list[0] as String
      val exp = pigeonVar_list[1] as Double?
      val topBidFiltered = pigeonVar_list[2] as Boolean?
      val winningFormat = pigeonVar_list[3] as String?
      val targetingKeywords = pigeonVar_list[4] as Map<String?, String?>?
      val nativeAdCacheId = pigeonVar_list[5] as String?
      return MultiformatBidResult(resultCode, exp, topBidFiltered, winningFormat, targetingKeywords, nativeAdCacheId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resultCode,
      exp,
      topBidFiltered,
      winningFormat,
      targetingKeywords,
      nativeAdCacheId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MultiformatBidResult
    return PrebidApiPigeonUtils.deepEquals(this.resultCode, other.resultCode) && PrebidApiPigeonUtils.deepEquals(this.exp, other.exp) && PrebidApiPigeonUtils.deepEquals(this.topBidFiltered, other.topBidFiltered) && PrebidApiPigeonUtils.deepEquals(this.winningFormat, other.winningFormat) && PrebidApiPigeonUtils.deepEquals(this.targetingKeywords, other.targetingKeywords) && PrebidApiPigeonUtils.deepEquals(this.nativeAdCacheId, other.nativeAdCacheId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.resultCode)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.exp)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.topBidFiltered)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.winningFormat)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.targetingKeywords)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.nativeAdCacheId)
    return result
  }
}

/**
 * Configuration for an in-stream video ad request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InstreamVideoAdRequestConfig (
  val configId: String,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstreamVideoAdRequestConfig {
      val configId = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return InstreamVideoAdRequestConfig(configId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configId,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InstreamVideoAdRequestConfig
    return PrebidApiPigeonUtils.deepEquals(this.configId, other.configId) && PrebidApiPigeonUtils.deepEquals(this.width, other.width) && PrebidApiPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.configId)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.width)
    result = 31 * result + PrebidApiPigeonUtils.deepHash(this.height)
    return result
  }
}
private open class PrebidApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializationResult.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RewardData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdEvent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAssetConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeEventTrackerConfig.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdRequestConfig.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdData.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExternalUserIdData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoParametersConfig.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MultiformatAdRequestConfig.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MultiformatBidResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstreamVideoAdRequestConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitializationResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RewardData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AdEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAssetConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeEventTrackerConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeAdRequestConfig -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeAdData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ExternalUserIdData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is VideoParametersConfig -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is MultiformatAdRequestConfig -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MultiformatBidResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is InstreamVideoAdRequestConfig -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Core SDK initialization and configuration.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PrebidMobileHostApi {
  fun initializeSdk(prebidServerUrl: String, accountId: String, callback: (Result<InitializationResult>) -> Unit)
  fun setTimeoutMillis(timeoutMillis: Long)
  fun setShareGeoLocation(share: Boolean)
  fun setPbsDebug(enabled: Boolean)
  fun setCustomHeaders(headers: Map<String, String>)
  fun setStoredAuctionResponse(response: String)
  fun clearStoredAuctionResponse()
  fun addStoredBidResponse(bidder: String, responseId: String)
  fun clearStoredBidResponses()
  fun setLogLevel(level: Long)
  fun setCreativeFactoryTimeout(timeout: Long)
  fun setCreativeFactoryTimeoutPreRenderContent(timeout: Long)
  fun setCustomStatusEndpoint(endpoint: String)
  fun setShouldAssignNativeAssetId(assign: Boolean)
  fun setFilterOutUncachedBids(filter: Boolean)
  fun setEidsPlacement(placement: String)
  fun setIncludeWinners(include: Boolean)
  fun setIncludeBidderKeys(include: Boolean)
  fun setExternalUserIds(userIds: List<ExternalUserIdData>)
  fun getExternalUserIds(): List<ExternalUserIdData>
  fun clearExternalUserIds()
  fun getSdkVersion(): String

  companion object {
    /** The codec used by PrebidMobileHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `PrebidMobileHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PrebidMobileHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.initializeSdk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prebidServerUrlArg = args[0] as String
            val accountIdArg = args[1] as String
            api.initializeSdk(prebidServerUrlArg, accountIdArg) { result: Result<InitializationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setTimeoutMillis$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutMillisArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setTimeoutMillis(timeoutMillisArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setShareGeoLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shareArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShareGeoLocation(shareArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setPbsDebug$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setPbsDebug(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCustomHeaders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val headersArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.setCustomHeaders(headersArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setStoredAuctionResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val responseArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setStoredAuctionResponse(responseArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearStoredAuctionResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearStoredAuctionResponse()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.addStoredBidResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderArg = args[0] as String
            val responseIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addStoredBidResponse(bidderArg, responseIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearStoredBidResponses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearStoredBidResponses()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setLogLevel(levelArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCreativeFactoryTimeout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setCreativeFactoryTimeout(timeoutArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCreativeFactoryTimeoutPreRenderContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setCreativeFactoryTimeoutPreRenderContent(timeoutArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setCustomStatusEndpoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val endpointArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setCustomStatusEndpoint(endpointArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setShouldAssignNativeAssetId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assignArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShouldAssignNativeAssetId(assignArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setFilterOutUncachedBids$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setFilterOutUncachedBids(filterArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setEidsPlacement$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placementArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setEidsPlacement(placementArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setIncludeWinners$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val includeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setIncludeWinners(includeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setIncludeBidderKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val includeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setIncludeBidderKeys(includeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.setExternalUserIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userIdsArg = args[0] as List<ExternalUserIdData>
            val wrapped: List<Any?> = try {
              api.setExternalUserIds(userIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.getExternalUserIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getExternalUserIds())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.clearExternalUserIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearExternalUserIds()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.PrebidMobileHostApi.getSdkVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkVersion())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Targeting and privacy settings.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TargetingHostApi {
  fun setSubjectToCOPPA(value: Boolean?)
  fun getSubjectToCOPPA(): Boolean?
  fun setSubjectToGDPR(value: Boolean?)
  fun getSubjectToGDPR(): Boolean?
  fun setGDPRConsentString(value: String?)
  fun getGDPRConsentString(): String?
  fun setPurposeConsents(value: String?)
  fun getPurposeConsents(): String?
  fun getDeviceAccessConsent(): Boolean?
  fun setUSPrivacyString(value: String?)
  fun getUSPrivacyString(): String?
  fun addUserKeyword(keyword: String)
  fun addUserKeywords(keywords: List<String>)
  fun removeUserKeyword(keyword: String)
  fun clearUserKeywords()
  fun getUserKeywords(): List<String>
  fun addAppKeyword(keyword: String)
  fun addAppKeywords(keywords: List<String>)
  fun removeAppKeyword(keyword: String)
  fun clearAppKeywords()
  fun addAppExtData(key: String, value: String)
  fun updateAppExtData(key: String, value: List<String>)
  fun removeAppExtData(key: String)
  fun clearAppExtData()
  fun addUserExtData(key: String, value: String)
  fun updateUserExtData(key: String, value: List<String>)
  fun removeUserExtData(key: String)
  fun clearUserExtData()
  fun addBidderToAccessControlList(bidderName: String)
  fun removeBidderFromAccessControlList(bidderName: String)
  fun clearAccessControlList()
  fun setGlobalOrtbConfig(ortbConfig: String?)
  fun getGlobalOrtbConfig(): String?
  fun setContentUrl(url: String?)
  fun setPublisherName(name: String?)
  fun setStoreUrl(url: String?)
  fun setDomain(domain: String?)

  companion object {
    /** The codec used by TargetingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `TargetingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TargetingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setSubjectToCOPPA$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean?
            val wrapped: List<Any?> = try {
              api.setSubjectToCOPPA(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getSubjectToCOPPA$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSubjectToCOPPA())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setSubjectToGDPR$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean?
            val wrapped: List<Any?> = try {
              api.setSubjectToGDPR(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getSubjectToGDPR$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSubjectToGDPR())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setGDPRConsentString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setGDPRConsentString(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getGDPRConsentString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGDPRConsentString())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setPurposeConsents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setPurposeConsents(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getPurposeConsents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPurposeConsents())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getDeviceAccessConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceAccessConsent())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setUSPrivacyString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setUSPrivacyString(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getUSPrivacyString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUSPrivacyString())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addUserKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.addUserKeywords(keywordsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeUserKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeUserKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearUserKeywords()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getUserKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUserKeywords())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addAppKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.addAppKeywords(keywordsArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeAppKeyword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keywordArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeAppKeyword(keywordArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAppKeywords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAppKeywords()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addAppExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.updateAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.updateAppExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeAppExtData(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAppExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAppExtData()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addUserExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.addUserExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.updateUserExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.updateUserExtData(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeUserExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeUserExtData(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearUserExtData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearUserExtData()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.addBidderToAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.addBidderToAccessControlList(bidderNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.removeBidderFromAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bidderNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeBidderFromAccessControlList(bidderNameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.clearAccessControlList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAccessControlList()
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setGlobalOrtbConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val ortbConfigArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setGlobalOrtbConfig(ortbConfigArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.getGlobalOrtbConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGlobalOrtbConfig())
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setContentUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setContentUrl(urlArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setPublisherName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setPublisherName(nameArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setStoreUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setStoreUrl(urlArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.TargetingHostApi.setDomain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val domainArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setDomain(domainArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Interstitial ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InterstitialAdHostApi {
  fun loadAd(adId: Long, configId: String, adFormats: List<String>?, videoConfig: VideoParametersConfig?, impOrtbConfig: String?)
  fun show(adId: Long)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by InterstitialAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `InterstitialAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InterstitialAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configIdArg = args[1] as String
            val adFormatsArg = args[2] as List<String>?
            val videoConfigArg = args[3] as VideoParametersConfig?
            val impOrtbConfigArg = args[4] as String?
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configIdArg, adFormatsArg, videoConfigArg, impOrtbConfigArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.show(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.InterstitialAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Rewarded ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface RewardedAdHostApi {
  fun loadAd(adId: Long, configId: String, impOrtbConfig: String?)
  fun show(adId: Long)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by RewardedAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `RewardedAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RewardedAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configIdArg = args[1] as String
            val impOrtbConfigArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configIdArg, impOrtbConfigArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.show(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.RewardedAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeAdHostApi {
  fun loadAd(adId: Long, config: NativeAdRequestConfig)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by NativeAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `NativeAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as NativeAdRequestConfig
            val wrapped: List<Any?> = try {
              api.loadAd(adIdArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.NativeAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Multiformat ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MultiformatAdHostApi {
  fun fetchDemand(adId: Long, config: MultiformatAdRequestConfig, callback: (Result<MultiformatBidResult>) -> Unit)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by MultiformatAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `MultiformatAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MultiformatAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.MultiformatAdHostApi.fetchDemand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as MultiformatAdRequestConfig
            api.fetchDemand(adIdArg, configArg) { result: Result<MultiformatBidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.MultiformatAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * In-stream video ad operations (Dart → Native).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InstreamVideoAdHostApi {
  fun fetchDemand(adId: Long, config: InstreamVideoAdRequestConfig, callback: (Result<MultiformatBidResult>) -> Unit)
  fun destroy(adId: Long)

  companion object {
    /** The codec used by InstreamVideoAdHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
    /** Sets up an instance of `InstreamVideoAdHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InstreamVideoAdHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.InstreamVideoAdHostApi.fetchDemand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val configArg = args[1] as InstreamVideoAdRequestConfig
            api.fetchDemand(adIdArg, configArg) { result: Result<MultiformatBidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PrebidApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PrebidApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.prebid_mobile_sdk.InstreamVideoAdHostApi.destroy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val adIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.destroy(adIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PrebidApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Callbacks for ad events from native to Flutter.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class AdFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AdFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrebidApiPigeonCodec()
    }
  }
  fun onAdEvent(eventArg: AdEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.prebid_mobile_sdk.AdFlutterApi.onAdEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PrebidApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
