import 'package:flutter/foundation.dart';

import 'ad_enums.dart';
import 'ad_listener.dart';
import 'generated/prebid_api.g.dart';

/// A fullscreen interstitial ad using Prebid rendering.
///
/// Create an instance, call [loadAd], and then [show] when ready.
/// Call [destroy] when the ad is no longer needed.
class PrebidInterstitialAd {
  @visibleForTesting
  static InterstitialAdHostApi api = InterstitialAdHostApi();
  static int _nextId = 0;

  final int _adId;

  /// The Prebid Server stored impression configuration ID.
  final String configId;

  /// The ad formats to request (banner, video, or both).
  final Set<AdFormat>? adFormats;

  /// Listener for interstitial ad events.
  final PrebidInterstitialAdListener? listener;

  /// Creates a [PrebidInterstitialAd].
  PrebidInterstitialAd({required this.configId, this.adFormats, this.listener})
    : _adId = _nextId++ {
    // Register this ad for receiving events
    _AdEventRouter.instance.registerInterstitial(_adId, this);
  }

  /// Load the interstitial ad.
  Future<void> loadAd() async {
    final formats = adFormats?.map((f) => f.name).toList();
    api.loadAd(_adId, configId, formats);
  }

  /// Show the interstitial ad.
  Future<void> show() async {
    api.show(_adId);
  }

  /// Destroy the interstitial ad and free resources.
  Future<void> destroy() async {
    _AdEventRouter.instance.unregister(_adId);
    api.destroy(_adId);
  }
}

/// A fullscreen rewarded ad using Prebid rendering.
///
/// Create an instance, call [loadAd], and then [show] when ready.
/// Call [destroy] when the ad is no longer needed.
class PrebidRewardedAd {
  @visibleForTesting
  static RewardedAdHostApi api = RewardedAdHostApi();
  static int _nextId = 1000000; // offset to avoid conflicts with interstitials

  final int _adId;

  /// The Prebid Server stored impression configuration ID.
  final String configId;

  /// Listener for rewarded ad events.
  final PrebidRewardedAdListener? listener;

  /// Creates a [PrebidRewardedAd].
  PrebidRewardedAd({required this.configId, this.listener})
    : _adId = _nextId++ {
    _AdEventRouter.instance.registerRewarded(_adId, this);
  }

  /// Load the rewarded ad.
  Future<void> loadAd() async {
    api.loadAd(_adId, configId);
  }

  /// Show the rewarded ad.
  Future<void> show() async {
    api.show(_adId);
  }

  /// Destroy the rewarded ad and free resources.
  Future<void> destroy() async {
    _AdEventRouter.instance.unregister(_adId);
    api.destroy(_adId);
  }
}

/// Routes ad events from native to the correct Dart ad instance.
///
/// Implements [AdFlutterApi] generated by Pigeon.
class _AdEventRouter implements AdFlutterApi {
  static final _AdEventRouter instance = _AdEventRouter._();
  _AdEventRouter._() {
    AdFlutterApi.setUp(this);
  }

  final Map<int, PrebidInterstitialAd> _interstitials = {};
  final Map<int, PrebidRewardedAd> _rewardeds = {};

  void registerInterstitial(int adId, PrebidInterstitialAd ad) {
    _interstitials[adId] = ad;
  }

  void registerRewarded(int adId, PrebidRewardedAd ad) {
    _rewardeds[adId] = ad;
  }

  void unregister(int adId) {
    _interstitials.remove(adId);
    _rewardeds.remove(adId);
  }

  @override
  void onAdEvent(AdEvent event) {
    final interstitial = _interstitials[event.adId];
    if (interstitial != null) {
      _handleInterstitialEvent(interstitial, event);
      return;
    }

    final rewarded = _rewardeds[event.adId];
    if (rewarded != null) {
      _handleRewardedEvent(rewarded, event);
    }
  }

  void _handleInterstitialEvent(PrebidInterstitialAd ad, AdEvent event) {
    final listener = ad.listener;
    if (listener == null) return;

    switch (event.eventName) {
      case 'onAdLoaded':
        listener.onAdLoaded?.call();
      case 'onAdFailed':
        listener.onAdFailed?.call(event.error ?? 'Unknown error');
      case 'onAdDisplayed':
        listener.onAdDisplayed?.call();
      case 'onAdDismissed':
        listener.onAdDismissed?.call();
      case 'onAdClicked':
        listener.onAdClicked?.call();
    }
  }

  void _handleRewardedEvent(PrebidRewardedAd ad, AdEvent event) {
    final listener = ad.listener;
    if (listener == null) return;

    switch (event.eventName) {
      case 'onAdLoaded':
        listener.onAdLoaded?.call();
      case 'onAdFailed':
        listener.onAdFailed?.call(event.error ?? 'Unknown error');
      case 'onAdDisplayed':
        listener.onAdDisplayed?.call();
      case 'onAdDismissed':
        listener.onAdDismissed?.call();
      case 'onAdClicked':
        listener.onAdClicked?.call();
      case 'onUserEarnedReward':
        if (event.reward != null) {
          listener.onUserEarnedReward?.call(
            PrebidReward(
              type: event.reward!.type ?? '',
              count: event.reward!.count ?? 0,
            ),
          );
        }
    }
  }
}
