// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "prebid_mobile_sdk",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .library(name: "prebid-mobile-sdk", targets: ["prebid_mobile_sdk"])
    ],
    dependencies: [
        // Generated by the Flutter tool (Flutter 3.44+, as the plugin template).
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        .package(url: "https://github.com/prebid/prebid-mobile-ios.git", from: "3.4.1"),
    ],
    targets: [
        .target(
            name: "prebid_mobile_sdk",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(name: "PrebidMobile", package: "prebid-mobile-ios"),
            ],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
