// Mocks generated by Mockito from annotations
// in prebid_mobile_sdk/test/mock_host_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:prebid_mobile_sdk/src/generated/prebid_api.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInitializationResult_0 extends _i1.SmartFake
    implements _i2.InitializationResult {
  _FakeInitializationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiformatBidResult_1 extends _i1.SmartFake
    implements _i2.MultiformatBidResult {
  _FakeMultiformatBidResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PrebidMobileHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrebidMobileHostApi extends _i1.Mock
    implements _i2.PrebidMobileHostApi {
  MockPrebidMobileHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.InitializationResult> initializeSdk(
    String? prebidServerUrl,
    String? accountId,
    String? nonTrackingUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initializeSdk, [
              prebidServerUrl,
              accountId,
              nonTrackingUrl,
            ]),
            returnValue: _i4.Future<_i2.InitializationResult>.value(
              _FakeInitializationResult_0(
                this,
                Invocation.method(#initializeSdk, [
                  prebidServerUrl,
                  accountId,
                  nonTrackingUrl,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.InitializationResult>);

  @override
  _i4.Future<void> setTimeoutMillis(int? timeoutMillis) =>
      (super.noSuchMethod(
            Invocation.method(#setTimeoutMillis, [timeoutMillis]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShareGeoLocation(bool? share) =>
      (super.noSuchMethod(
            Invocation.method(#setShareGeoLocation, [share]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPbsDebug(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setPbsDebug, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomHeaders(Map<String, String>? headers) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomHeaders, [headers]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStoredAuctionResponse(String? response) =>
      (super.noSuchMethod(
            Invocation.method(#setStoredAuctionResponse, [response]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearStoredAuctionResponse() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredAuctionResponse, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addStoredBidResponse(String? bidder, String? responseId) =>
      (super.noSuchMethod(
            Invocation.method(#addStoredBidResponse, [bidder, responseId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearStoredBidResponses() =>
      (super.noSuchMethod(
            Invocation.method(#clearStoredBidResponses, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLogLevel(int? level) =>
      (super.noSuchMethod(
            Invocation.method(#setLogLevel, [level]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCreativeFactoryTimeout(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setCreativeFactoryTimeout, [timeout]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCreativeFactoryTimeoutPreRenderContent(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setCreativeFactoryTimeoutPreRenderContent, [
              timeout,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getCreativeFactoryTimeout() =>
      (super.noSuchMethod(
            Invocation.method(#getCreativeFactoryTimeout, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getCreativeFactoryTimeoutPreRenderContent() =>
      (super.noSuchMethod(
            Invocation.method(#getCreativeFactoryTimeoutPreRenderContent, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setPrebidServerAccountId(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#setPrebidServerAccountId, [accountId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getPrebidServerAccountId() =>
      (super.noSuchMethod(
            Invocation.method(#getPrebidServerAccountId, []),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getPrebidServerAccountId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> setPrebidServerUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setPrebidServerUrl, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPrebidServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getPrebidServerUrl, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setUseCacheForReportingWithRenderingApi(bool? use) =>
      (super.noSuchMethod(
            Invocation.method(#setUseCacheForReportingWithRenderingApi, [use]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getUseCacheForReportingWithRenderingApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUseCacheForReportingWithRenderingApi, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setCustomStatusEndpoint(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomStatusEndpoint, [endpoint]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShouldAssignNativeAssetId(bool? assign) =>
      (super.noSuchMethod(
            Invocation.method(#setShouldAssignNativeAssetId, [assign]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setFilterOutUncachedBids(bool? filter) =>
      (super.noSuchMethod(
            Invocation.method(#setFilterOutUncachedBids, [filter]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setEidsPlacement(String? placement) =>
      (super.noSuchMethod(
            Invocation.method(#setEidsPlacement, [placement]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIncludeWinners(bool? include) =>
      (super.noSuchMethod(
            Invocation.method(#setIncludeWinners, [include]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIncludeBidderKeys(bool? include) =>
      (super.noSuchMethod(
            Invocation.method(#setIncludeBidderKeys, [include]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAuctionSettingsId(String? settingsId) =>
      (super.noSuchMethod(
            Invocation.method(#setAuctionSettingsId, [settingsId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDisableStatusCheck(bool? disable) =>
      (super.noSuchMethod(
            Invocation.method(#setDisableStatusCheck, [disable]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setEventDelegateEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setEventDelegateEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLogListenerEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setLogListenerEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLocationUpdatesEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setLocationUpdatesEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getLocationUpdatesEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationUpdatesEnabled, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setDebugLogFileEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDebugLogFileEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getDebugLogFileEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getDebugLogFileEnabled, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<int?> getTimeoutMillisDynamic() =>
      (super.noSuchMethod(
            Invocation.method(#getTimeoutMillisDynamic, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<void> setSendSharedId(bool? send) =>
      (super.noSuchMethod(
            Invocation.method(#setSendSharedId, [send]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ExternalUserIdData?> getSharedId() =>
      (super.noSuchMethod(
            Invocation.method(#getSharedId, []),
            returnValue: _i4.Future<_i2.ExternalUserIdData?>.value(),
          )
          as _i4.Future<_i2.ExternalUserIdData?>);

  @override
  _i4.Future<void> resetSharedId() =>
      (super.noSuchMethod(
            Invocation.method(#resetSharedId, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setExternalUserIds(List<_i2.ExternalUserIdData>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#setExternalUserIds, [userIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ExternalUserIdData>> getExternalUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#getExternalUserIds, []),
            returnValue: _i4.Future<List<_i2.ExternalUserIdData>>.value(
              <_i2.ExternalUserIdData>[],
            ),
          )
          as _i4.Future<List<_i2.ExternalUserIdData>>);

  @override
  _i4.Future<void> clearExternalUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#clearExternalUserIds, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getTimeoutMillis() =>
      (super.noSuchMethod(
            Invocation.method(#getTimeoutMillis, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> getPbsDebug() =>
      (super.noSuchMethod(
            Invocation.method(#getPbsDebug, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> getShareGeoLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getShareGeoLocation, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, String>> getCustomHeaders() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomHeaders, []),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<String?> getStoredAuctionResponse() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredAuctionResponse, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, String>> getStoredBidResponses() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredBidResponses, []),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<String?> getCustomStatusEndpoint() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomStatusEndpoint, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> getShouldAssignNativeAssetId() =>
      (super.noSuchMethod(
            Invocation.method(#getShouldAssignNativeAssetId, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> getFilterOutUncachedBids() =>
      (super.noSuchMethod(
            Invocation.method(#getFilterOutUncachedBids, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getEidsPlacement() =>
      (super.noSuchMethod(
            Invocation.method(#getEidsPlacement, []),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getEidsPlacement, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> getIncludeWinners() =>
      (super.noSuchMethod(
            Invocation.method(#getIncludeWinners, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> getIncludeBidderKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getIncludeBidderKeys, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getAuctionSettingsId() =>
      (super.noSuchMethod(
            Invocation.method(#getAuctionSettingsId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> getDisableStatusCheck() =>
      (super.noSuchMethod(
            Invocation.method(#getDisableStatusCheck, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getSdkVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getSdkVersion, []),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getSdkVersion, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getOmsdkVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getOmsdkVersion, []),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#getOmsdkVersion, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> releaseAds() =>
      (super.noSuchMethod(
            Invocation.method(#releaseAds, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TargetingHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTargetingHostApi extends _i1.Mock implements _i2.TargetingHostApi {
  MockTargetingHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> setSubjectToCOPPA(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSubjectToCOPPA, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getSubjectToCOPPA() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectToCOPPA, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setSubjectToGDPR(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSubjectToGDPR, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> getSubjectToGDPR() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectToGDPR, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> setGDPRConsentString(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGDPRConsentString, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getGDPRConsentString() =>
      (super.noSuchMethod(
            Invocation.method(#getGDPRConsentString, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setPurposeConsents(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPurposeConsents, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPurposeConsents() =>
      (super.noSuchMethod(
            Invocation.method(#getPurposeConsents, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool?> getPurposeConsent(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#getPurposeConsent, [index]),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<bool?> getDeviceAccessConsent() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceAccessConsent, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<bool> isAllowedAccessDeviceData() =>
      (super.noSuchMethod(
            Invocation.method(#isAllowedAccessDeviceData, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setUSPrivacyString(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUSPrivacyString, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUSPrivacyString() =>
      (super.noSuchMethod(
            Invocation.method(#getUSPrivacyString, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> addUserKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#addUserKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addUserKeywords(List<String>? keywords) =>
      (super.noSuchMethod(
            Invocation.method(#addUserKeywords, [keywords]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserKeywords, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getUserKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#getUserKeywords, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addAppKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#addAppKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addAppKeywords(List<String>? keywords) =>
      (super.noSuchMethod(
            Invocation.method(#addAppKeywords, [keywords]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAppKeyword(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppKeyword, [keyword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAppKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppKeywords, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getAppKeywords() =>
      (super.noSuchMethod(
            Invocation.method(#getAppKeywords, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addAppExtData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#addAppExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateAppExtData(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAppExtData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppExtData, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAppExtData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppExtData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addUserExtData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#addUserExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserExtData(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserExtData, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserExtData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserExtData, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserExtData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserExtData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserExt(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setUserExt, [json]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserExt() =>
      (super.noSuchMethod(
            Invocation.method(#getUserExt, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> addBidderToAccessControlList(String? bidderName) =>
      (super.noSuchMethod(
            Invocation.method(#addBidderToAccessControlList, [bidderName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeBidderFromAccessControlList(String? bidderName) =>
      (super.noSuchMethod(
            Invocation.method(#removeBidderFromAccessControlList, [bidderName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAccessControlList() =>
      (super.noSuchMethod(
            Invocation.method(#clearAccessControlList, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setGlobalOrtbConfig(String? ortbConfig) =>
      (super.noSuchMethod(
            Invocation.method(#setGlobalOrtbConfig, [ortbConfig]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getGlobalOrtbConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalOrtbConfig, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setPublisherName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setPublisherName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStoreUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setStoreUrl, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDomain(String? domain) =>
      (super.noSuchMethod(
            Invocation.method(#setDomain, [domain]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setAppName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setAppName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSourceApp(String? sourceApp) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceApp, [sourceApp]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setItunesId(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#setItunesId, [itunesId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBundleName(String? bundleName) =>
      (super.noSuchMethod(
            Invocation.method(#setBundleName, [bundleName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getBundleName() =>
      (super.noSuchMethod(
            Invocation.method(#getBundleName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setOmidPartnerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setOmidPartnerName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setOmidPartnerVersion(String? version) =>
      (super.noSuchMethod(
            Invocation.method(#setOmidPartnerVersion, [version]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserLatLng(double? latitude, double? longitude) =>
      (super.noSuchMethod(
            Invocation.method(#setUserLatLng, [latitude, longitude]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserLatLng() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserLatLng, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLocationPrecision(int? precision) =>
      (super.noSuchMethod(
            Invocation.method(#setLocationPrecision, [precision]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, List<String>>> getAppExtData() =>
      (super.noSuchMethod(
            Invocation.method(#getAppExtData, []),
            returnValue: _i4.Future<Map<String, List<String>>>.value(
              <String, List<String>>{},
            ),
          )
          as _i4.Future<Map<String, List<String>>>);

  @override
  _i4.Future<List<String>> getAccessControlList() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessControlList, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<String?> getPublisherName() =>
      (super.noSuchMethod(
            Invocation.method(#getPublisherName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getStoreUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getStoreUrl, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getDomain() =>
      (super.noSuchMethod(
            Invocation.method(#getDomain, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getOmidPartnerName() =>
      (super.noSuchMethod(
            Invocation.method(#getOmidPartnerName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getOmidPartnerVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getOmidPartnerVersion, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> getSendSharedId() =>
      (super.noSuchMethod(
            Invocation.method(#getSendSharedId, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<double>?> getUserLatLng() =>
      (super.noSuchMethod(
            Invocation.method(#getUserLatLng, []),
            returnValue: _i4.Future<List<double>?>.value(),
          )
          as _i4.Future<List<double>?>);

  @override
  _i4.Future<int?> getLocationPrecision() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPrecision, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<String?> getSourceApp() =>
      (super.noSuchMethod(
            Invocation.method(#getSourceApp, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getItunesId() =>
      (super.noSuchMethod(
            Invocation.method(#getItunesId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [InterstitialAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterstitialAdHostApi extends _i1.Mock
    implements _i2.InterstitialAdHostApi {
  MockInterstitialAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(
    int? adId,
    String? configId,
    List<String>? adFormats,
    _i2.VideoParametersConfig? videoConfig,
    String? impOrtbConfig,
    String? globalOrtbConfig,
    _i2.FullscreenControlsConfig? controls,
    String? pbAdSlot,
    int? adPosition,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [
              adId,
              configId,
              adFormats,
              videoConfig,
              impOrtbConfig,
              globalOrtbConfig,
              controls,
              pbAdSlot,
              adPosition,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#show, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RewardedAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRewardedAdHostApi extends _i1.Mock implements _i2.RewardedAdHostApi {
  MockRewardedAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(
    int? adId,
    String? configId,
    List<String>? adFormats,
    _i2.VideoParametersConfig? videoConfig,
    String? impOrtbConfig,
    String? globalOrtbConfig,
    _i2.FullscreenControlsConfig? controls,
    String? pbAdSlot,
    int? adPosition,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [
              adId,
              configId,
              adFormats,
              videoConfig,
              impOrtbConfig,
              globalOrtbConfig,
              controls,
              pbAdSlot,
              adPosition,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> show(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#show, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NativeAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeAdHostApi extends _i1.Mock implements _i2.NativeAdHostApi {
  MockNativeAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<void> loadAd(int? adId, _i2.NativeAdRequestConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, [adId, config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadFromCacheId(int? adId, String? cacheId) =>
      (super.noSuchMethod(
            Invocation.method(#loadFromCacheId, [adId, cacheId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> performClick(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#performClick, [adId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [MultiformatAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiformatAdHostApi extends _i1.Mock
    implements _i2.MultiformatAdHostApi {
  MockMultiformatAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.MultiformatBidResult> fetchDemand(
    int? adId,
    _i2.MultiformatAdRequestConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDemand, [adId, config]),
            returnValue: _i4.Future<_i2.MultiformatBidResult>.value(
              _FakeMultiformatBidResult_1(
                this,
                Invocation.method(#fetchDemand, [adId, config]),
              ),
            ),
          )
          as _i4.Future<_i2.MultiformatBidResult>);

  @override
  _i4.Future<void> setAutoRefreshInterval(int? adId, int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoRefreshInterval, [adId, seconds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAutoRefresh(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#stopAutoRefresh, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumeAutoRefresh(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeAutoRefresh, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> activateBannerImpressionTracker(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#activateBannerImpressionTracker, [adId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<int>?> findPrebidCreativeSize(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#findPrebidCreativeSize, [adId]),
            returnValue: _i4.Future<List<int>?>.value(),
          )
          as _i4.Future<List<int>?>);

  @override
  _i4.Future<bool> activateBannerSKAdNetwork(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#activateBannerSKAdNetwork, [adId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> activateInterstitialSKAdNetwork(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#activateInterstitialSKAdNetwork, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> activateSKOverlay(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#activateSKOverlay, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dismissSKOverlay(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#dismissSKOverlay, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [InstreamVideoAdHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstreamVideoAdHostApi extends _i1.Mock
    implements _i2.InstreamVideoAdHostApi {
  MockInstreamVideoAdHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.MultiformatBidResult> fetchDemand(
    int? adId,
    _i2.InstreamVideoAdRequestConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDemand, [adId, config]),
            returnValue: _i4.Future<_i2.MultiformatBidResult>.value(
              _FakeMultiformatBidResult_1(
                this,
                Invocation.method(#fetchDemand, [adId, config]),
              ),
            ),
          )
          as _i4.Future<_i2.MultiformatBidResult>);

  @override
  _i4.Future<void> destroy(int? adId) =>
      (super.noSuchMethod(
            Invocation.method(#destroy, [adId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> generateInstreamUriForGam(
    String? adUnitId,
    List<int>? sizes,
    Map<String, String>? keywords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateInstreamUriForGam, [
              adUnitId,
              sizes,
              keywords,
            ]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#generateInstreamUriForGam, [
                  adUnitId,
                  sizes,
                  keywords,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);
}
