name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install workspace dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze all packages
        run: dart run melos exec -- flutter analyze

      - name: Run tests
        run: dart run melos exec --dir-exists="test" -- flutter test

      - name: Build Example APK
        working-directory: ./example
        run: flutter build apk --debug

      - name: Build Example iOS
        working-directory: ./example
        run: flutter build ios --no-codesign --debug
